name: CUPS AirPrint
version: 1.1.7
slug: cups-airprint
url: https://github.com/mastria/hassio-addons/tree/main/cups-airprint
description: CUPS print server with AirPrint support for network printing
arch:
  - aarch64
  - amd64
startup: services
boot: auto
# Acesso USB para impressoras
usb: true
# udev necessário para detecção automática de dispositivos USB
udev: true
init: false
homeassistant_api: true
# Rede do host necessária para broadcast do AirPrint
host_network: true
# Privilégios necessários para acesso a dispositivos USB e raw sockets
privileged:
  - SYS_RAWIO
  - NET_ADMIN
  - NET_RAW
ports:
  631/tcp: 631
  5353/udp: null
ports_description:
  631/tcp: CUPS web interface and IPP printing
  5353/udp: mDNS/Bonjour for AirPrint discovery
webui: http://[HOST]:631
map:
  - addon_config:rw
options:
  log_level: info
schema:
  log_level: list(debug|info|warning|error)
